program sem2reader;

{%ToDo 'sem2reader.todo'}

uses
  Forms,
  Windows,
  basic in 'basic.pas' {frmBasic},
  main in 'main.pas' {frmMain},
  borders in 'borders.pas',
  box in 'box.pas',
  calendar in 'calendar.pas',
  crc in 'crc.pas',
  get_border in 'get_border.pas',
  get_calc1 in 'get_calc1.pas',
  get_calc2 in 'get_calc2.pas',
  get_canal_spec in 'get_canal_spec.pas',
  get_cntcanmon in 'get_cntcanmon.pas',
  get_contacts3 in 'get_contacts3.pas',
  get_control in 'get_control.pas',
  get_correct in 'get_correct.pas',
  get_current in 'get_current.pas',
  get_digit in 'get_digit.pas',
  get_digit_enbl in 'get_digit_enbl.pas',
  get_enggrpday in 'get_enggrpday.pas',
  get_enggrpmon in 'get_enggrpmon.pas',
  get_esc in 'get_esc.pas',
  get_extended4 in 'get_extended4.pas',
  get_group in 'get_group.pas',
  get_impcanday in 'get_impcanday.pas',
  get_impcanhou in 'get_impcanhou.pas',
  get_impcanmnt in 'get_impcanmnt.pas',
  get_impcanmon in 'get_impcanmon.pas',
  get_infogps in 'get_infogps.pas',
  get_maxgrpday in 'get_maxgrpday.pas',
  get_maxgrpmon in 'get_maxgrpmon.pas',
  get_params in 'get_params.pas',
  get_phone in 'get_phone.pas',
  get_pulse_hou in 'get_pulse_hou.pas',
  get_recalc in 'get_recalc.pas',
  get_records in 'get_records.pas',
  get_relaxs in 'get_relaxs.pas',
  get_schedule in 'get_schedule.pas',
  get_time in 'get_time.pas',
  get_trans_eng in 'get_trans_eng.pas',
  get_version in 'get_version.pas',
  kernel in 'kernel.pas',
  ports in 'ports.pas',
  progress in 'progress.pas',
  realz in 'realz.pas',
  sinput in 'sinput.pas',
  soutput in 'soutput.pas',
  support in 'support.pas',
  terminal in 'terminal.pas',
  timez in 'timez.pas',
  get_events in 'get_events.pas',
  get_extended5 in 'get_extended5.pas',
  get_tariffs in 'get_tariffs.pas',
  get_infosmk in 'get_infosmk.pas',
  get_correct20 in 'get_correct20.pas',
  get_border2 in 'get_border2.pas',
  get_version2 in 'get_version2.pas',
  get_digit2 in 'get_digit2.pas',
  get_queryCF in 'get_queryCF.pas',
  get_queryFF19 in 'get_queryFF19.pas',
  get_phone2 in 'get_phone2.pas',
  get_port in 'get_port.pas',
  get_correct21 in 'get_correct21.pas',
  get_ace in 'get_ace.pas',
  get_correct3 in 'get_correct3.pas',
  get_extended44 in 'get_extended44.pas',
  get_powcanhou in 'get_powcanhou.pas',
  get_powgrphou in 'get_powgrphou.pas',
  get_extended6 in 'get_extended6.pas',
  get_extended43 in 'get_extended43.pas',
  get_engcanday in 'get_engcanday.pas',
  get_engcanmon in 'get_engcanmon.pas',
  get_border1 in 'get_border1.pas',
  get_enggrphou in 'get_enggrphou.pas',
  get_output_delay in 'get_output_delay.pas',
  ok in 'ok.pas' {frmOK},
  yesno in 'yesno.pas' {frmYesNo},
  get_memory0 in 'get_memory0.pas',
  get_memory2 in 'get_memory2.pas',
  get_memory1 in 'get_memory1.pas',
  t_memory in 't_memory.pas',
  get_memory23 in 'get_memory23.pas',
  get_memory22 in 'get_memory22.pas',
  get_memory21 in 'get_memory21.pas',
  get_memory12 in 'get_memory12.pas',
  get_correct_limit in 'get_correct_limit.pas',
  get_link_errors in 'get_link_errors.pas',
  get_hou_check in 'get_hou_check.pas',
  get_defcanmon in 'get_defcanmon.pas',
  get_defcanday in 'get_defcanday.pas',
  get_defgrpday in 'get_defgrpday.pas',
  get_defgrpmon in 'get_defgrpmon.pas',
  get_defcanhou in 'get_defcanhou.pas',
  get_defcanday2 in 'get_defcanday2.pas',
  get_defcanmon2 in 'get_defcanmon2.pas',
  get_defgrpday2 in 'get_defgrpday2.pas',
  get_defgrpmon2 in 'get_defgrpmon2.pas',
  get_enggrpday_def in 'get_enggrpday_def.pas',
  get_enggrpmon_def in 'get_enggrpmon_def.pas',
  get_maxgrpday_def in 'get_maxgrpday_def.pas',
  get_maxgrpmon_def in 'get_maxgrpmon_def.pas',
  get_enggrpprevhou_def in 'get_enggrpprevhou_def.pas',
  get_powgrpprevhou_def in 'get_powgrpprevhou_def.pas',
  borders2 in 'borders2.pas',
  get_params2 in 'get_params2.pas',
  get_params3 in 'get_params3.pas',
  get_diagram in 'get_diagram.pas',
  get_gaps1 in 'get_gaps1.pas',
  get_gaps2 in 'get_gaps2.pas',
  get_gaps3 in 'get_gaps3.pas',
  get_p79_errors in 'get_p79_errors.pas',
  get_defgrphou in 'get_defgrphou.pas',
  get_extended7 in 'get_extended7.pas',
  get_answer_disable in 'get_answer_disable.pas',
  get_answer_enable in 'get_answer_enable.pas',
  get_stat1 in 'get_stat1.pas',
  get_device23 in 'get_device23.pas',
  get_overflow_hou in 'get_overflow_hou.pas',
  get_border3 in 'get_border3.pas',
  get_decret in 'get_decret.pas',
  get_start in 'get_start.pas',
  get_bulk in 'get_bulk.pas',
  get_current4 in 'get_current4.pas',
  get_records_map in 'get_records_map.pas',
  get_checkup in 'get_checkup.pas',
  get_checkup_events_day in 'get_checkup_events_day.pas',
  get_checkup_hou in 'get_checkup_hou.pas',
  get_checkup_defects_day in 'get_checkup_defects_day.pas',
  get_checkup_events_mon in 'get_checkup_events_mon.pas',
  get_checkup_defects_mon in 'get_checkup_defects_mon.pas',
  get_checkup_days in 'get_checkup_days.pas',
  get_extended4t in 'get_extended4t.pas',
  get_enggrpday_x2 in 'get_enggrpday_x2.pas',
  get_enggrpmon_x2 in 'get_enggrpmon_x2.pas',
  get_extended4t_x2 in 'get_extended4t_x2.pas',
  get_extended5_x2 in 'get_extended5_x2.pas',
  get_extended4_x2 in 'get_extended4_x2.pas',
  get_extended44_x2 in 'get_extended44_x2.pas',
  get_engfrac1 in 'get_engfrac1.pas',
  get_engfrac2 in 'get_engfrac2.pas',
  get_memory3 in 'get_memory3.pas',
  get_extended6_x2 in 'get_extended6_x2.pas',
  get_extended7_x2 in 'get_extended7_x2.pas',
  get_errorlink in 'get_errorlink.pas',
  get_extended0 in 'get_extended0.pas';

{$R *.RES}

var
  hMutex: THandle;

begin
  hMutex := CreateMutex(nil, True, 'sem2reader');
  if GetLastError <> 0 then
  begin
    WrnBox('Программа ''sem2reader'' уже запущена !');
    ReleaseMutex(hMutex);
    Exit;
  end;

  Application.Initialize;
  Application.CreateForm(TfrmMain, frmMain);
  Application.Run;

  ReleaseMutex(hMutex);
  if GetLastError <> 0 then ;
end.
